# Generated by Django 2.2.3 on 2019-07-10 21:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=255, unique=True)),
                ('floor_data', models.TextField()),
                ('file_with_data', models.FilePathField()),
                ('indexed_names', django_mysql.models.ListTextField(models.CharField(max_length=255), size=10000)),
            ],
        ),
    ]
